# Generated by Django 4.0.4 on 2022-06-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0003_recipe_hints_recipe_portions_recipe_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='details',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='hints',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='portions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time', models.IntegerField(default=20)),
                ('portions', models.IntegerField(default=1)),
                ('details', models.CharField(blank=True, default='', max_length=120)),
                ('instructions', models.TextField(blank=True, default='')),
                ('hints', models.TextField(blank=True, default='')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='ingredient_in_food', to='Recipe.recipeingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='food_in_recipe', to='Recipe.food'),
        ),
    ]
