# Generated by Django 4.0.4 on 2022-06-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_remove_recipe_details_remove_recipe_hints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
    ]
