# Generated by Django 4.0.4 on 2022-06-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0006_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients_temp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
