# Generated by Django 4.0.4 on 2022-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0007_food_ingredients_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='details',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='food',
            name='portions',
            field=models.CharField(default='1', max_length=12),
        ),
    ]
