# Generated by Django 3.2.4 on 2021-10-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='zoom_access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='zoom_refresh_token',
            field=models.TextField(default=''),
        ),
    ]
