# Generated by Django 3.2.4 on 2021-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20211015_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='zoom_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='zoom_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
