# Generated by Django 3.2.4 on 2021-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profilemodel_credit_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='threshold',
            field=models.TextField(default='High'),
        ),
    ]
