# Generated by Django 3.2.4 on 2022-01-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_profilemodel_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='credit_month',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
