# Generated by Django 3.2.4 on 2022-05-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_alter_profilemodel_credit_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='credit_month',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
